/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Domain.PalabraTexto;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 *
 * @author Josec
 */
public class VentanaArbolaTexto extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaArbolaTexto
     */
    private ArrayList<PalabraTexto> palabras;
    private String[] vector;
    public VentanaArbolaTexto() {
        this.vector=new String[100000];
        initComponents();
        ArbolaTexto();
    }
    
    public void ArbolaTexto(){
        String lista="";
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;

      try {

         archivo = new File ("ArchivoArbol.txt");
         fr = new FileReader (archivo);
         br = new BufferedReader(fr);

         String linea;
         String[] temp;
         while((linea=br.readLine())!=null){
            temp=linea.split(",");
            for(int i=1;i<temp.length;i++){
                this.vector[Integer.parseInt(temp[i])]=temp[0];
            }
         }
         
      }
      catch(Exception e){
         e.printStackTrace();
      }finally{

         try{                    
            if( null != fr ){   
               fr.close();     
            }                  
         }catch (Exception e2){ 
            e2.printStackTrace();
         }
      }
      int cont=0;
      while(this.vector[cont]!=null){
          lista+=this.vector[cont]+" ";
          cont++;
          if(cont%15==0){
              lista+="\n";
          }
      }
      this.jTextArea1.setText(lista);
      
      FileWriter fichero = null;
        PrintWriter pw = null;
        try
        {
            fichero = new FileWriter("ArbolaTexto.txt");
            pw = new PrintWriter(fichero);

            cont=0;
            while(vector[cont]!=null){
                pw.print(this.vector[cont]+" ");
                cont++;
                if(cont%15==0)
                    pw.println();
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           if (null != fichero)
              fichero.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
